spring:
    datasource:
        username: beer_order_service
        password: '{cipher}ffd2a5c65165e4e7ad6e27113f2c3d219bf38ea663d24521be9183a98d802bbc'
        url: jdbc:mysql://127.0.0.1:3306/beer_order_service_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
logging:
    level:
#        org.hibernate:
#            SQL: DEBUG
#            type.descriptor.sql.BasicBinder: TRACE
        com.zaxxer.hikari:
            HikariConfig: TRACE
