spring:
    datasource:
        username: beer_service
        password: password
        url: jdbc:mysql://127.0.0.1:3306/beer_service_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
logging:
    level:
#        org.hibernate:
#            SQL: DEBUG
#            type.descriptor.sql.BasicBinder: TRACE
        com.zaxxer.hikari:
            HikariConfig: TRACE
