spring:
    datasource:
        username: beer_inventory_service
        password: '{cipher}d7293d04818d0e2ed8993be8342a4e6bb8ce0647d6742594e38d8d483276685a'
        url: jdbc:mysql://127.0.0.1:3306/beer_inventory_service_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    artemis:
        user: artemis
        password: '{cipher}a43216aa6beec440870710eebd980ad09387bf97deb9dc116d127d40b9ba802e'
logging:
    level:
        #        org.hibernate:
        #            SQL: DEBUG
        #            type.descriptor.sql.BasicBinder: TRACE
        com.zaxxer.hikari:
            HikariConfig: TRACE
